# Generated by Django 5.2.4 on 2025-07-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(default='premium', max_length=10)),
                ('auto_salon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_account', to='auto_salon.autosalonmodel')),
            ],
            options={
                'db_table': 'premium_account',
            },
        ),
    ]
